#!/usr/bin/env python3
"""Convert the committed brand SVG to an Android VectorDrawable.

The supplied SVG is the source of truth for the small in-app brand mark. It
already contains the intended 25 paths and nine gradients, so this generator
maps those primitives directly instead of retracing a raster image or
approximating its colours. Keeping the source viewBox and intrinsic aspect
ratio also prevents square ImageViews from stretching the taller artwork.

Only the SVG subset used by ``docs/logo/app-logo.svg`` is accepted on purpose:
linear gradients, solid RGB fills, paths, and zero translation transforms.
Unexpected authoring changes fail loudly rather than silently degrading the
logo during conversion.
"""

from __future__ import annotations

import argparse
import hashlib
import pathlib
import re
import xml.etree.ElementTree as ET


ROOT = pathlib.Path(__file__).resolve().parents[2]
MASTER = ROOT / "docs/logo/app-logo.svg"
TARGET = ROOT / "app/src/main/res/drawable/ic_logo.xml"

SVG = "{http://www.w3.org/2000/svg}"
INTRINSIC_HEIGHT_DP = 24.0


def source_hash() -> str:
    return hashlib.sha256(MASTER.read_bytes()).hexdigest()


def number(value: float) -> str:
    return f"{value:.3f}".rstrip("0").rstrip(".")


def android_color(value: str) -> str:
    match = re.fullmatch(r"rgb\(\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)\s*\)", value)
    if match is None:
        if re.fullmatch(r"#[0-9A-Fa-f]{6,8}", value):
            return value.upper()
        raise ValueError(f"unsupported SVG colour: {value}")
    channels = tuple(int(channel) for channel in match.groups())
    if any(channel > 255 for channel in channels):
        raise ValueError(f"invalid SVG colour: {value}")
    return "#" + "".join(f"{channel:02X}" for channel in channels)


def parse_master() -> tuple[float, float, dict[str, ET.Element], list[ET.Element]]:
    root = ET.parse(MASTER).getroot()
    view_box = [float(value) for value in root.get("viewBox", "").split()]
    if len(view_box) != 4 or view_box[:2] != [0.0, 0.0]:
        raise ValueError("brand SVG must have a zero-origin four-value viewBox")
    width, height = view_box[2:]
    if width <= 0 or height <= 0:
        raise ValueError("brand SVG viewBox must be positive")

    gradients = {
        gradient.attrib["id"]: gradient
        for gradient in root.findall(f".//{SVG}linearGradient")
    }
    paths = root.findall(f".//{SVG}path")
    if not gradients or not paths:
        raise ValueError("brand SVG must contain gradients and paths")
    return width, height, gradients, paths


def gradient_xml(gradient: ET.Element) -> list[str]:
    required = ("x1", "y1", "x2", "y2")
    if any(name not in gradient.attrib for name in required):
        raise ValueError(f"gradient {gradient.get('id')} is missing coordinates")
    lines = [
        "        <aapt:attr name=\"android:fillColor\">",
        "            <gradient",
        f"                android:startX=\"{gradient.attrib['x1']}\"",
        f"                android:startY=\"{gradient.attrib['y1']}\"",
        f"                android:endX=\"{gradient.attrib['x2']}\"",
        f"                android:endY=\"{gradient.attrib['y2']}\"",
        "                android:type=\"linear\">",
    ]
    stops = gradient.findall(f"{SVG}stop")
    if not stops:
        raise ValueError(f"gradient {gradient.get('id')} has no stops")
    for stop in stops:
        if stop.get("stop-opacity", "1") != "1":
            raise ValueError(f"gradient {gradient.get('id')} uses unsupported opacity")
        lines.append(
            "                <item "
            f"android:offset=\"{stop.attrib['offset']}\" "
            f"android:color=\"{android_color(stop.attrib['stop-color'])}\" />"
        )
    lines.extend(("            </gradient>", "        </aapt:attr>"))
    return lines


def render() -> str:
    width, height, gradients, paths = parse_master()
    intrinsic_width = INTRINSIC_HEIGHT_DP * width / height
    output = [
        '<?xml version="1.0" encoding="utf-8"?>',
        '<!-- Generated by tools/brand/generate_logo_vector.py.',
        '     Brand exception: converted directly from docs/logo/app-logo.svg, not a Lucide icon.',
        f'     Source-SHA256: {source_hash()} -->',
        '<vector xmlns:android="http://schemas.android.com/apk/res/android"',
        '    xmlns:aapt="http://schemas.android.com/aapt"',
        '    xmlns:tools="http://schemas.android.com/tools"',
        f'    android:width="{number(intrinsic_width)}dp"',
        f'    android:height="{number(INTRINSIC_HEIGHT_DP)}dp"',
        f'    android:viewportWidth="{number(width)}"',
        f'    android:viewportHeight="{number(height)}"',
        '    tools:ignore="VectorPath">',
    ]

    for path in paths:
        transform = path.get("transform")
        if transform not in (None, "translate(0,0)", "translate(0, 0)"):
            raise ValueError(f"unsupported path transform: {transform}")
        path_data = " ".join(path.attrib["d"].split())
        fill = path.attrib["fill"]
        gradient_match = re.fullmatch(r"url\(#([^)]+)\)", fill)
        if gradient_match:
            gradient_id = gradient_match.group(1)
            if gradient_id not in gradients:
                raise ValueError(f"missing SVG gradient: {gradient_id}")
            output.extend(("    <path", f'        android:pathData="{path_data}">'))
            output.extend(gradient_xml(gradients[gradient_id]))
            output.append("    </path>")
        else:
            output.extend(
                (
                    "    <path",
                    f'        android:fillColor="{android_color(fill)}"',
                    f'        android:pathData="{path_data}" />',
                )
            )

    output.extend(("</vector>", ""))
    return "\n".join(output)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    generated = render()
    if args.check:
        if not TARGET.exists() or TARGET.read_text() != generated:
            print(f"error: {TARGET.relative_to(ROOT)} is stale")
            return 1
        print(f"ok: {TARGET.relative_to(ROOT)} is up to date")
        return 0
    TARGET.write_text(generated)
    print(f"wrote {TARGET.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
